### ISSUE TITLE
Does this client library allow me to make requests to the new Natural Language APIs?

### ISSUE THREAD

**Issue by aligajani** [google/google-api-php-client#1001]

**Comment by bshaffer** [comment]
Yes, see the class files [here](https://github.com/google/google-api-php-client-services/blob/v0.5/CloudNaturalLanguageAPI.php) and [here](https://github.com/google/google-api-php-client-services/blob/v0.5/CloudNaturalLanguageAPI). Please note the name of this API may change to `CloudNaturalLanguage` (dropping the API) in the future, since the current name is not consistent with the other API class names.
