### ISSUE TITLE
Adding alt=csv not working

### ISSUE THREAD

**Issue by lomholdt** [google/google-api-php-client#1076]
Adding the alt parameter with value csv does not seem to work using this php client. 

http://stackoverflow.com/questions/40379366/add-alt-parameter-while-generating-reports-from-adexchange-seller-api

**Comment by hfuccillo** [comment]
I'm having the same issue! 
When I set alt = 'CSV' it throws an exception: throw new Google_Service_Exception("Invalid json in service response: $body");
In /src/Google/Http/REST.php line 86.

**Comment by etchen99** [comment]
This line here says alt is fine:

https://github.com/google/google-api-php-client-services/blob/a80b8ba13130960f1850542c587de165b4480389/src/Google/Service/AdExchangeSeller/Resource/AccountsReports.php#L31

However, these lines are problematic because they try to decode the csv as json:

https://github.com/google/google-api-php-client/blob/43996f09df274158fd04fce98e8a82effe5f3717/src/Google/Http/REST.php#L125-L129

One solution is to add another condition here:

https://github.com/google/google-api-php-client/blob/43996f09df274158fd04fce98e8a82effe5f3717/src/Google/Service/Resource.php#L218-L220

so that it works for `csv`, in addition to `media`.  Don't know if it would break other code though.  If this is fine, I can add this and make a pull request.

Then you'd access the csv using:
```
$report = $service->accounts_reports->generate($name, $startDate,
                $endDate, $optParams);
$csv = (string) $report->getBody();
```

Works for me.

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
