### ISSUE TITLE
Hi, Can anyone tell me how to set ancesstor of an entity and save it using this google datatstore library?

### ISSUE THREAD

**Issue by mandeep3012** [google/google-api-php-client#1135]

**Comment by bshaffer** [comment]
@mandeep3012 Use the [`google-cloud-php`](https://github.com/googlecloudplatform/google-cloud-php) instead of this one to access datastore:

```sh
composer require google/cloud
```

This library is handwritten to be much more usable, and the documentation is way better:

 - [API Documentation](http://googlecloudplatform.github.io/google-cloud-php/#/docs/v0.20.1/datastore/key?method=ancestor)
 - [Official Documentation](https://cloud.google.com/datastore/docs/how-to)
 - [Code Snippets](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/datastore/api/src/functions/concepts.php)
 
Using the `google-cloud-php` library, setting an ancestor would look something like this:

```php
$datastore = new Google\Cloud\Datastore\DatastoreClient([
    'projectId' => $projectId, // your project ID
]);
$key = $datastore->key('Person', 'Bob');
$key->ancestor('Parents', 'Joe');
$key->ancestor('Grandparents', 'Barb');
```
