### ISSUE TITLE
Drive API direct link problem

### ISSUE THREAD

**Issue by yedort** [google/google-api-php-client#1143]
I need get a direct link to a file by its file id.

I tried chunked download/stream and it has a quota.

Then I tried to get the webContentLink field, it asks you to scan viruses first.

So there is no direct link. What am I supposed to do?

**Comment by net-tools** [comment]
Have you tried files.get with `alt=media` standard parameter ?

[Drive v3 reference](https://developers.google.com/drive/v3/web/manage-downloads)

**Comment by chadismydad** [comment]
I'm having a similar issue. Although I've tried using the `alt=media` parameter, it downloads a file with a random jumbled name. It looks like the file id, actually.

**Comment by mattwhisenhunt** [comment]
This issue is not related to this client library at all.
As @net-tools says, you could use this library on a PHP server to download the files there and then give out the link to that server.

I think Google Drive API is designed to not have direct links but I know very little about that particular API.
