### ISSUE TITLE
[proposal] Set Auth Config without JSON file 

### ISSUE THREAD

**Issue by rogervila** [google/google-api-php-client#1166]
Hello, 

The `setAuthConfig()` method reads the json config file content and parses it with `json_decode`

https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L848

I'd like to have a method to pass the json values directly. Something like `setAuthConfigJson()`.

If it's ok, I'd like to make a PR.

Thank you.

**Comment by stevenscg** [comment]
@rogervila `setAuthConfig` accepts an array or a file. Does that solve your issue?

**Comment by rogervila** [comment]
Almost. My idea was to directly pass the json string, without having to `json_decode` the string before passing it.

I know is not a big issue, but I like to skip this kind of steps before using a package method.

**Comment by jacurtis** [comment]
Thanks to @stevenscg for pointing out that you can pass in an array.  I was trying to do the same thing as @rogervila in that I wanted to create the authjson myself (as opposed to fetching a file).

I was creating the json in another method by making a PHP array and `json_encode`ing it into a JSON string. Found out that it attempts to fetch the file instead of recognizing it as a JSON string.

But now that I know I can pass an array directly in, that makes it easier. Just removed the `json_encode()` so that it was getting an actual array and now it works great.  I see no need to change the package.

**Comment by bshaffer** [comment]
Yes, this is WAI. I do not see a big win in accepting a json-encoded string. It's either the string path to a file or a PHP array representing the credentials. Thanks guys!
