### ISSUE TITLE
Getting `redirect_uri_mismatch` error

### ISSUE THREAD

**Issue by hellboy81** [google/google-api-php-client#1198]
I get always `redirect_uri_mismatch`  :

![9efbae50-0023-11e7-9079-8293a6b6eca3](https://cloud.githubusercontent.com/assets/341600/24900764/2e1e7884-1ea5-11e7-828c-cbabaa6368d5.png)

`client_secret.json` schema:

```json
{"web":
    {"client_id":"....apps.googleusercontent.com",
    "project_id":"my-oauth-project-id",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"myTopClientSecret",
    "redirect_uris":["https://www.my.net/index.php","http://www.my.net/index.php"],
    "javascript_origins":["https://www.my.net"]
    }
   }
````

See [myboshi.net](http://www.myboshi.net)

**Comment by bshaffer** [comment]
Follow the error message and verify the redirect URI registered in your console (`https://www.my.net/index.php`) matches the one used in your application code. I.e.:

```php
$redirectUri = 'https://www.my.net/index.php';
$client = new Google_Client();
$client->setRedirectUri($redirectUri);

// .. if an access token doesn't exist
$authUrl = $client->createAuthUrl();
header('Location: ' . $authUrl);
```

See [this example](https://github.com/google/google-api-php-client/blob/master/examples/simple-file-upload.php#L31) for more information.

**Comment by PatelAshish1** [comment]
In my case it was www and non-www URL. Actual site had www URL and the Authorized Redirect URIs in Google Developer Console had non-www URL. Hence, there was mismatch in redirect URI. I solved it by updating Authorized Redirect URIs in Google Developer Console to www URL.

Other common URI mismatch are:

Using http:// in Authorized Redirect URIs and https:// as actual URL, or vice-versa
Using trailing slash (http://example.com/) in Authorized Redirect URIs and not using trailing slash (http://example.com) as actual URL, or vice-versa
Here are the step-by-step screenshots of Google Developer Console so that it would be helpful for those who are getting it difficult to locate the developer console page to update redirect URIs.

1. Go to https://console.developers.google.com
2. Select your Project
3. Click on The Menu Icon
Find All step At [Here](https://icetutor.com/question/google-oauth-2-authorization-error-redirect_uri_mismatch/)

**Comment by joandylevi** [comment]
Go to https://console.developers.google.com
Select your Project
Click on The Menu Icon
Click on API Manager menu

Full Answer Available At [Here](https://icetutor.com/question/google-oauth-2-authorization-error-redirect_uri_mismatch/)
