### ISSUE TITLE
Google API Client Auth Exception Invalid email or User ID

### ISSUE THREAD

**Issue by taqiofficial** [google/google-api-php-client#1207]
**Hi All!**

I'm using this library with symfony to get list some events from google a specific calendar. all of sudden without any change in code i got below error;

```
  [Google_Auth_Exception]                             
  Error refreshing the OAuth2 token, message: '{      
    "error" : "invalid_grant",                        
    "error_description" : "Invalid email or User ID"  
  }' 
```
with version
`google/apiclient 1.0.6-beta`

The error is on this line 

```
        return new \Google_Auth_AssertionCredentials(
            $this->container->getParameter('google_client_id'),
            [ Google_Service_Calendar::CALENDAR ],
            file_get_contents($this->container->getParameter('google_p12_path')),
            'notasecret',
            'http://oauth.net/grant_type/jwt/1.0/bearer',
            $calendarId
        );
```
Please help, is this is from library of google api's ?
Thank you!

**Comment by bshaffer** [comment]
Hey @taqiofficial ! 
Unfortunately version `v1.x` of this library is no longer supported. Please upgrade to `v2.x`. 

As for the error, I do not know what the issue is, but it could have to do with using `.p12` files, which are not recommended and should only be used for backwards compatibility.

Some extra help: the error above occurs when the email address sent in with the access token is not found. See [here](https://community.bittitan.com/kb/Pages/Errorinvalid_grant,%20DescriptionInvalid%20email%20or%20User%20ID,%20Uri%20Cause%20One%20or%20more%20errors%20occurred.aspx).

**Comment by taqiofficial** [comment]
@bshaffer The issue it was working 3 days ago, and all of sudden start giving this error.

**Comment by taqiofficial** [comment]
+ plus I am not sending any user email, there is just client email that is valid and calendar id , The google calendar Id whom i want to get list of events.
