### ISSUE TITLE
Street View Publish API

### ISSUE THREAD

**Issue by upendtu** [google/google-api-php-client#1226]
Hi,
Currently I am working on street View Publish API ,

Can anybody please explain me in details how I can upload the images and make the connection between panorama using street view publish API ?

Any help will be much appreciated......................

**Comment by strarsis** [comment]
@upendtu: In related library [google-api-php-client-services](https://github.com/google/google-api-php-client-services) Street View Publish API is [mentioned in code](https://github.com/google/google-api-php-client-services/tree/0805897f3435f9eea73ce21da9d55f51c69c1171/src/Google/Service/StreetViewPublish).

**Comment by mattwhisenhunt** [comment]
I found [this page](https://developers.google.com/maps/documentation/javascript/streetview#CreatingPanoramas). For more/better help with this PHP api-client I am going to need more details about the error or obstacle you are running into.

**Comment by strarsis** [comment]
@mattwhisenhunt: An example for publishing/updating photospheres using the google-api-php-client together with google-api-php-client-services, including minimal OAuth, would be a great starting point for me.

**Comment by mattwhisenhunt** [comment]
I agree and going forward working samples in even more languages for even more APIs should be available, they are already [starting to emerge](https://cloud.google.com/php/) for some APIs. Because this client library is in maintenance mode, back-filling examples for every API is too low priority.

A short term workaround for you might be using a [different API's PHP example](https://developers.google.com/gmail/api/quickstart/php) (for some working OAuth code) and the [Python example](https://developers.google.com/streetview/publish/libraries) as a kind of mash up starting point.
