### ISSUE TITLE
Google drive batch copy

### ISSUE THREAD

**Issue by dungvaph03374** [google/google-api-php-client#1375]
Currently i'm using this to copy drive files to my account but after 300 - 500 files i got error "User rate limit exceeded" until next day.
I'm also tried batching request, still getting error
![image](https://user-images.githubusercontent.com/9255898/35207252-8579a83c-ff74-11e7-8eea-20c044d7bf3b.png)

**Comment by LindaLawton** [comment]
There is a limit to the number of requests that you can make in a day and batch does not help you with this limit.

Lets say my quota is 20 and I send four batch requests with five requests in each request to batch.   I have still blown out my quota of 20 because the total number of requests within the batch is 20.

There is no purpose to batching other then removing send time on your server.     As for the file upload quota it is not documented because google tends to change it a lot.    Last I heard it was around 50 per user.   You seem to have been lucky to get more then that.

This isnt an issue with the client library this is an issue with Quotas in Google APIs
