### ISSUE TITLE
How to use quotaUser 

### ISSUE THREAD

**Issue by momark** [google/google-api-php-client#1385]
Does this Client library allows setting Standard Query Parameter "quotaUser"?
Ref: https://developers.google.com/analytics/devguides/reporting/core/v4/parameters

It is important to be used when calling the API through CRON jobs on behalf of several users. https://developers.google.com/analytics/devguides/reporting/core/v3/limits-quotas

But I can't seem to figure out how to pass this query parameter. Should it be part of batchget call like this:
$optParams['quotaUser'] = "ABCXYZ123";
$analytics->reports->batchGet( $body, $optParams  )

Or during initialize
$client->set... ?

**Comment by LindaLawton** [comment]
Yes quota user should be working with this library.  

    $optParams['quotaUser'] = "ABCXYZ123";
    $analytics->reports->batchGet( $body, $optParams )

Your code looks correct to me.  

You haven't mentioned which quota error you are getting with this.  However remember the quota with the Google Analytics API is based upon the view and not upon the user.   Also due to the batching nature if you are sending more then one report you can easily hit a quota.    If its coming from the same IP address going against the same view using a different quotaUser i dont think its going to help you.

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.
