### ISSUE TITLE
How i can use importRows in my project?

### ISSUE THREAD

**Issue by MarceloBonifazio** [google/google-api-php-client#1388]
I have this code:

		$out = fopen('php://output', 'w');
		fputcsv($out, 
			array('Location')
		);
		foreach($objects as $object){
			fputcsv($out, 
				array(
					$ad->objectLat.",".$ad->objectLnt,
				)
			);
		}
		$test = fclose($out);
		
		$client = new Google_Client();
		$client->useApplicationDefaultCredentials();
		$client->setScopes('https://www.googleapis.com/auth/fusiontables');
		$service = new Google_Service_Fusiontables($client);
		$service->table->importRows($test);

I looked in the documentation, but could not find the reference

**Comment by LindaLawton** [comment]
This appears to be a question about how to use the client library rather than an issue with the client library.  Please post questions on stack overflow using the tag [google-api-php-clinet](https://stackoverflow.com/questions/tagged/google-api-php-client) someone there should be able to assist you.  

@mattwhisenhunt  recommend closing this.

**Comment by mattwhisenhunt** [comment]
Thanks for opening this issue. It looks like you have received an answer on SO. I'm happy to reopen this thread, just add a comment.
