### ISSUE TITLE
Any chance we can get Google_Service_Walletobjects added?

### ISSUE THREAD

**Issue by clevertree** [google/google-api-php-client#1486]
Hy there. I'm not sure how to use the new GPay api via composer or git. Any suggestions? Right now I'm including it manually
..src/Google/Service/Walletobjects.php

Thanks!

**Comment by mattwhisenhunt** [comment]
Hi @clevertree. Where are you finding Walletobjects.php? Please link to which specific API you are trying to access. It looks to me like Walletobjects is probably deprecated and currently the Google Pay API does not have a generally published definition/discovery document (otherwise it would show up on [API Explorer](https://developers.google.com/apis-explorer/#p/)).

**Comment by clevertree** [comment]
Thanks for the response Matt. Here's the sample code where I found the library:
https://github.com/google-pay/s2ap-quickstart-php/tree/master/google-api-client/src/Google/Service

Also I received this library from Google via zipfile after signing up for the new GPay API, so maybe this hasn't been released yet. I might also be misunderstanding something. Thanks!

**Comment by mattwhisenhunt** [comment]
Thanks cool. I didn't know this library was being vendor'd in other projects like that. Depending on how close you want to stick to the code provided you can either do it manually as you suggest or the line that handles the rest of the includes in the example is https://github.com/google-pay/s2ap-quickstart-php/blob/master/header.php#L27

**Comment by mattwhisenhunt** [comment]
Let me know if you have anymore questions.

**Comment by quinncomendant** [comment]
I'm not sure why this issue was closed? It makes sense to include the Walletobjects classes in with google-api-php-client. 

I'm building an integration with Google Wallet passes, and this file is promoted on [this page](https://developers.google.com/wallet/generic/resources/libraries#client-libraries). It's currently very cumbersome to manually integrate this file, and it requires google-api-php-client anyways. It would be logical to get both with a single `composer require google/apiclient` command.
