### ISSUE TITLE
Youtube Update API V3 : status.embeddable and status.license  is not editable

### ISSUE THREAD

**Issue by samisalow** [google/google-api-php-client#448]
I can not change status.license and status.embeddable, using youtube api V3, can you help me

**Comment by samisalow** [comment]
help me please

**Comment by ianbarber** [comment]
Can't help with API specific questions on this tracker - best to ask your question (ideally with code) on StackOverflow: http://stackoverflow.com/questions/tagged/youtube-api. In general though, see if it works properly via the API explorer: https://developers.google.com/apis-explorer/#p/ - if it doesn't, then the issue is with the API. If it does, please file a bug with the specific differences you're seeing in the requests and we can try and resolve any issue in the library.
