### ISSUE TITLE
Webmasters API cannot list my verified sites

### ISSUE THREAD

**Issue by Janmay** [google/google-api-php-client#450]
I want to list my verified sites using google-api-php-client webmasters api, and it worked well before. But somehow it gets empty results now.

What is happening?

**Comment by ianbarber** [comment]
Might be worth checking with the webmasters API team - this tracker is for general issues with the client library. Also could have been a temporary issues - in general try and see if it works via the API explorer: https://developers.google.com/apis-explorer/#p/ - if it does, but not with the client library there may be a bug in the library, otherwise its likely an issue with the service.

**Comment by Janmay** [comment]
It works well via the API explorer. With the client library I use service account to access API, and it's ok for Analytics API and Site Verification API.  There is not warning or error to access Webmasters API. It just like that I have not verified sites, which actually I does, and via Site Verification API I can get them.

**Comment by ianbarber** [comment]
I'm not familiar with the webmasters tools, but have you granted access to your service account email address (as you would have with analytics)? Service accounts are there own user, effectively, so they can't see *your* data without being specifically granted access.

**Comment by Janmay** [comment]
I have already verified my service account email as owner of sites. It did not work.

**Comment by ianbarber** [comment]
Might be worth checking with the webmaster tools team - its not an API i've used directly.

**Comment by shuler** [comment]
I've added service account email as a simple user with restricted permission in Google Search Console and it worked for me
