### ISSUE TITLE
Fatal Error: Google_Service_SQLAdmin_OperationError

### ISSUE THREAD

**Issue by SnowB1** [google/google-api-php-client#477]
The file at /src/Google/Service/SQLAdmin.php contains two classes both named: Google_Service_SQLAdmin_OperationError causing an error.

**Comment by ianbarber** [comment]
Urgh. That is presumable the generator mangling two names together into the same PHP name.

**Comment by whatthejeff** [comment]
Looks like the unit tests would've caught this. Might make sense to add them to the build process that generates these classes.

**Comment by ianbarber** [comment]
Yeah, though that would result in the public versions being invisibly out of date, which isn't much better. Maybe we could have the script open a GH issue automatically or similar. Taking a quick look at the discovery doc, it looks like operation error is only defined once, so I'm not totally sure why we're generating both a model and a collection.

**Comment by ianbarber** [comment]
So, this is a painful one. The issue is that there is an anonymous collection object in Operation called error, and there is a schema called OperationError. Unfortunately, the top level code generator gives them the same name - OperationError. I'm going to see if there is a workaround, but because its part of the generic rather than language specific infrastructure the solutions may not be fast.

**Comment by ianbarber** [comment]
Fixed! Travis ran the last 2 commits out of order so it still looks failing, but the build should now be passing - the generation OperationError collection has been renamed OperationErrors.
