### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by alexpoon2000** [google/google-api-php-client#536]
Can anyone get the refresh token?

	// create google client object
	$client = new Google_Client();
	$client->setClientId($client_id);
	$client->setClientSecret($client_secret);
	$client->setRedirectUri($redirect_url);
	$client->setAccessType('offline');
	$client->setScopes(array('https://www.googleapis.com/auth/drive'));

	// get token
    if (isset($_GET['code'])) {
    	$client->authenticate($_GET['code']);  
    	$_SESSION['token'] = $client->getAccessToken();
    	$_SESSION['token_start_time'] = time();
		header('Location: '.$redirect_url);
		exit;
    }

The token I got didn't included the refresh token. And I try to call $client->revokeToken($_SESSION['token']). It doesn't revoke the the token.

**Comment by ianbarber** [comment]
Are you sure you're not overriding your $_SESSION object somewhere? Could you paste in a working, complete code example we can use to verify?

**Comment by chancegarcia** [comment]
I noticed the same issue when re-running the auth process.
On the second run through of 
```php
 $client->authenticate($_GET['code']); 
```
will return an access token but fail to give you a refresh token as requested.

This seems to be because you haven't manually revoked the token through the google account/security settings (https://security.google.com/settings/security/permissions).

**Comment by ianbarber** [comment]
Shouldn't need to be a revoke, but it could well be because the user was signed in without a consent screen - for 2nd and future sign ins the consent screen may be skipped and the refresh token not returned. You can trigger a consent screen with the prompt parameter, which should result in a refresh token.
