### ISSUE TITLE
Is it possible to fetch all gmail messages?

### ISSUE THREAD

**Issue by malikperang** [google/google-api-php-client#558]
Hi, I would like to know if it could fetch all gmail messages because when I'm tried it,always returns **"Failed to connect to www.googleapis.com port 443: Network is unreachable
Error: An Internal Error Has Occurred"** and the result are less than actual total amount of email on gmail.

best regards,

**Comment by ianbarber** [comment]
Thats an odd error. Were you able to fetch a single message, or make other successful API calls?

**Comment by nebadom** [comment]
I did it by using try / catch because every once in a while google servers fails... and when that happens, you end up with just a fraction of the messages.

Try using this:

		try {
			$messages = $service->users_messages->listUsersMessages('me',$optParams);
		} catch (Exception $e) {			// if any error is detected
			return false;				// exits the function
		}

What I did was to get the nextpage token in EVERY query, then retrieve 100 messages ID, then try again using the nextpage token retrieved in the previous pass.

And I've been able to get ALL the messages. It works, it's just a pain to do it.

**Comment by tmatsuo** [comment]
@nebadom Sorry for the late reply, but is this issue still relevant? Do you want to have a whole list of messages? If so, there is a concern with memory consumption. It is a far better design to use the nextpage token. Ideally it is great if all the `List*` methods returns a generator for the whole result, but since this library supports PHP 5.4, it is difficult for now.

Maybe we should stop supporting PHP 5.5 or older. @bshaffer WDYT?

**Comment by nebadom** [comment]
I did it the "hard way": I retrieve every nextpage token and then retrieved every 500 items in batches, using a "task". Doing so it could take several minutes processing it, but it worked for the purpose I wanted it.

**Comment by tmatsuo** [comment]
@nebadom Oh, maybe you're on App Engine PHP standard? I think the generator approach won't work well on App Engine Standard beyond the Deadline.
