### ISSUE TITLE
401 Login Required for Drive API

### ISSUE THREAD

**Issue by shivasurya** [google/google-api-php-client#700]
Respected,

i would like to access my own account via API key.

$client = new Google_Client();
			$client->setApplicationName("Drive key");
			$client->setDeveloperKey("XXXXXX");
			$service = new Google_Service_Drive($client);
			$file = new Google_Service_Drive_DriveFile();

			$result = $service->files->insert($file, array(
				'data' => file_get_contents($name),
				'mimeType' => 'application/octet-stream',
				'uploadType' => 'media'
				));
			 var_dump($result);

i get result as 401 login required. may i know the clear cut documentation for this because i own the api key and obviously i'm inserting file it into my drive account.
why should i go for giving permission ? is there any explanation ?

**Comment by sqrrrl** [comment]
The API key only identifies the calling application, not the content owner. Drive operates on user owned data and since the owner of the application and the owner of the content are (usually) not the same, oauth is used to delegate permission and identify which account we're operating on.

To your question about why not infer the content owner from the application? For one, applications can have multiple owners. That makes any attempt to infer the correct account ambiguous (arbitrarily pick one) at best, expensive (if we want things like the union of all owners) at worst. Contrary to what you think, from the server's perspective it's not at all obvious which account your inserting into when you're making an unauthorized request.

**Comment by bshaffer** [comment]
see the [simple-file-upload](https://github.com/google/google-api-php-client/blob/master/examples/simple-file-upload.php#L55) example for how to grant user-level permission and upload to your drive account.

You'll need to grant your app access to your user account using an OAuth2 authorization flow. Once you've done this, the application will be granted an access token and refresh token, and will be able to maintain access to your account using these.

**Comment by shivasurya** [comment]
thanks!
