### ISSUE TITLE
GuzzleHttp required version

### ISSUE THREAD

**Issue by mikepmtl** [google/google-api-php-client#708]
I am getting the following composer error:
google/apiclient dev-master requires guzzlehttp/guzzle 5.2.* -> no matching package found.

That is a very restrictive version for guzzlehttp.

I had the API working with version 6.1.0 but not tested for all calls, but work for what I was using it for (Live API Analytics)

Is there anyway this can be changed to ">=5.2.0", or something less restrictive?

**Comment by bshaffer** [comment]
Unfortunately, since Guzzle 6 breaks all BC with Guzzle 5, this is not possible. 

I agree this is very restrictive... we can probably make the library compatible with `~5.0` but Guzzle 6 is a whole separate undertaking.

If you are unable to resolve this problem, update your composer to use Google API Client `v1.1.6` or `dev-v1-master`
