### ISSUE TITLE
where is autoload.php?

### ISSUE THREAD

**Issue by LindaLawton** [google/google-api-php-client#716]
It seams that something has changed recently i cant find autoload.php anymore.

My code normally uses. 

     require_once 'Google/autoload.php';

Your [samples](https://github.com/google/google-api-php-client/blob/master/examples/url-shortener.php) now use 

    include_once __DIR__ . '/../vendor/autoload.php';

Which also doesn't appear to exist.    Any tips on what we should be using now?  This kind of broke my tutorials again.   [Google Service Account with PHP](http://www.daimto.com/google_service_account_php/)

**Comment by mTorres** [comment]
That's because the master branch is using [composer](http://getcomposer.org). Install composer and then run ```composer require "google/apiclient:~2.0@dev"``` from the terminal located on your project root directory. After that you'll have on your project root the vendor subfolder with the autoload file that you must include.

Or you could just download the v1 :-)

**Comment by LindaLawton** [comment]
Ahh thank you.  Is v1 staying?  I will change my links in the tutorial to that then.

**Comment by bshaffer** [comment]
@LindaLawton yes, `v2` (at the time of this writing) is at `v2.0.0-RC1`, so unless you specifically want to upgrade, I'd recommend using `v1.1.6` of this library. The docs you've mentioned will be updated once `v2` is stable (`v2.0.0`). 

Also, I recommend using composer even for `v1`, so that your code does not update unexpectedly:

```
"google/apiclient": "~v1.1.6"
```

**Comment by LindaLawton** [comment]
@bshaffer adding composer to my tutorials seams a bit over kill.    I would rather keep them pure code but i will look into it.

**Comment by bshaffer** [comment]
@LindaLawton Composer will allow the code in your repository to represent only the "pure code" of your application, as I can only assume you're committing your dependent libraries directly into your repository. 

You can instruct users to install your application using [`composer create-project`](https://getcomposer.org/doc/03-cli.md#create-project) rather than `git clone` so there are no extra steps. The community is very familiar with composer, so I doubt many would consider it overkill.

Either way, Good luck!

**Comment by LindaLawton** [comment]
I don't have an application I have a tutorial.   I am looking for the best way of creating tutorials that wont brake when you guys update stuff.     I would appreciate your advice in that.   This is the second time I have had to update all of my tutorials because of a change.  The first was when you added autoload.php.

No code is committed anywhere besides to the WordPress page.
