### ISSUE TITLE
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by verbruggenalex** [google/google-api-php-client#742]
Previously I was working on localhost without SSL without any problems. But lately when trying to authenticate I get the following error:

>GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate in GuzzleHttp\Exception\RequestException::wrapException() (line 51 of C:\wamp\www\development.xxx\sites\all\libraries\google-api-php-client\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php).

On my webserver with SSL everything worked just fine. So I tried using SSL locally to no avail. I also tried using __*$client->setDefaultOption('verify', false);*__ to which I get following error:

>Fatal error: Call to undefined method Google_Client::setDefaultOption()

Is there still a possibility to authenticate without SSL. Just for the sake of allowing people to test out stuff locally without the use of SSL?

Ps: I apologize in advance if this is a non-issue that belongs on stackoverflow. But I really don't know what caused this change in behaviour.

**Comment by bshaffer** [comment]
We do not recommend disabling SSL. Instead you should find where the Root
CA of the machine and add it to Guzzle, or if SSL isn't needed, make
requests on port 80.

If your project WAS working with SSL enabled, and now it isn't, I would
definitely suggest investigating that root cause first.

That being said, it is possible to disable SSL verification in guzzle with
the following command:

$client->getHttpClient()->setDefaultOption('verify', false);

As this command COMPLETELY NULLIFIES THE SECURITY USEFULNESS OF SSL and
HTTPS, please use wisely (and preferably not at all)

**Comment by verbruggenalex** [comment]
The only difference I can come up with between my dev server and localhost is I'm working on port 8080 and 4433 on my localhost. Could that interfere with Guzzle requests?

PS: I'm just writing a Drupal module for uploading videos to YouTube. And I want people to be able to disable SSL verification just for testing purposes if they encounter the same problem as I am. I'm well aware never to do this on a production server.

**Comment by bshaffer** [comment]
Well, if you're making an HTTPS request on your local machine, you'll need a self-signed certificate and you'll want to add your certificate authority in guzzle. The path to the self-signed certificate can be passed to the `verify` option instead of a boolean in order to do this.

There's extra overhead to get this working, but it's more secure and reliable in the long run.

**Comment by jatasya** [comment]
you can checkout the below link

[(http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate/34883260#34883260)]

**Comment by AdnanHussainTurki** [comment]
You can check out this video:
https://youtu.be/fWyV9Kt3wUM
