### ISSUE TITLE
GAE: Guzzle complains over missing CA bundle

### ISSUE THREAD

**Issue by Abbe98** [google/google-api-php-client#743]
When running `master-dev` in the Google App Engine SDK sometimes you get the following error from Guzzle:

`No system CA bundle could be found in any of the the common system locations.`

The following code would for example trigger it:
````php
$client = new Google_Client();
$client->setApplicationName('Application-Name');
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json');
$client->useApplicationDefaultCredentials();

$service = new Google_Service_Analytics($client);
$accounts = $service->management_accounts->listManagementAccounts()
```

**Comment by mTorres** [comment]
This is because Guzzle couldn't find the CA bundle of your system to check the SSL certificates. See the [Guzzle FAQ for more info](http://docs.guzzlephp.org/en/latest/faq.html#why-am-i-getting-an-ssl-verification-error).

Also, if you have to create your own CA bundle (you must update that periodically!) check [this](http://curl.haxx.se/docs/caextract.html).

I'm not sure if from the Google Client side there's anything doable to solve this (probably lots of work for little gain?)

**Comment by Abbe98** [comment]
When looking into it I guess it's a issue with the GAE SDK, the SDK should emulate the CA bundle used on GAE it self.
