### ISSUE TITLE
[Google_Auth] Version 2 RC 5 does not work on PHP 5.4

### ISSUE THREAD

**Issue by swordbeta** [google/google-api-php-client#883]
Version 2 RC 5 does not work on PHP 5.4 because GuzzleHttp 5.3 is not PSR-7 compliant https://github.com/guzzle/guzzle/blob/5.3/src/Client.php#L7; they're not only typehinting their own RequestInterface but also using own methods not implemented in PSR-7.
Example code: (as documented on this repo here: https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#google_auth_abstract-classes-have-been-removed)

```
$httpClient = $client->authorize();
$request = new GuzzleHttp\Psr7\Request('GET', $url);
$httpClient->send($request);
```

Error:

```
Catchable Fatal Error: Argument 1 passed to GuzzleHttp\Client::send() must implement interface GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given
Fatal Error: Call to undefined method GuzzleHttp\Psr7\Request::getConfig() in /vagrant/app/Vendor/guzzlehttp/guzzle/src/Client.php on line 160
```

Using GuzzleHttp\Message\RequestInterface does not seem to work for some reason, as the following:

```
$httpClient = $client->authorize();
$request = new GuzzleHttp\Message\Request('GET', $url);
$httpClient->send($request);
```

gives the following response:

```
Login required
```

This renders version 2.0.0-RC5 not usable on PHP 5.4. Tested using the Dfareporting Google service.

**Comment by bshaffer** [comment]
Hmm, the first will definitely not work because you're directly calling the v5.x Guzzle Client with the Psr7 request, and is WAD. However, the following should work:

As for the second, this should definitely work. Can you paste the full version of your code? [No authentication is attached if you do not provide anything](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L361), so this could be the problem.

**Comment by bshaffer** [comment]
We have tests that cover this:

 - [Developer Key](https://github.com/google/google-api-php-client/blob/master/tests/Google/ClientTest.php#L32)
 - [Access Token](https://github.com/google/google-api-php-client/blob/master/tests/Google/ClientTest.php#L107)
 - [Application Default Credentials](https://github.com/google/google-api-php-client/blob/master/tests/Google/ClientTest.php#L373)

So the problem is most likely in your implementation.

**Comment by swordbeta** [comment]
Full version of code:

```
$googleClient = new Google_Client();
$googleClient->setAuthConfigFile('doubleClick.json');
$googleClient->addScope([
	'https://www.googleapis.com/auth/dfareporting',
	'https://www.googleapis.com/auth/dfatrafficking',
	'https://www.googleapis.com/auth/userinfo.email',
]);
$googleClient->setRedirectUri('http://myredirecturl.com');
$googleClient->setAccessType('offline');
$googleClient->setApprovalPrompt('force');
$googleClient->setAccessToken(array(
	'access_token' => 'myAccessToken',
	'expires_in' => 3600,
	'created' => strtotime('2016-03-04 XX:XX:XX') - 3600
));

$url = 'https://www.googleapis.com/dfareporting/v2.4/reports/39164646/files/220870887?alt=media';
$httpClient = $googleClient->authorize();
$request = new GuzzleHttp\Message\Request('GET', $url);
$httpClient->send($request);
```

The access token is valid as I'm able to call endpoints of the DCM/DFA API.
I checked if the `ScopedAccessTokenSubscriber` is attached to the `GuzzleClient` and it is (as the unit test is also asserting), however the onBefore method is never called. What could be the cause of this?

**Comment by bshaffer** [comment]
@swordbeta thank you for updating this! That is definitely a tricky bug. But yes that makes sense, if you want to manipulate the `GuzzleHttp\Message\Request` object directly, you'll want to call [`Guzzle_Client::createRequest`](https://github.com/guzzle/guzzle/blob/5.3/src/Client.php#L111), and then the emitters will be attached.
