### ISSUE TITLE
Is this PHP 5.4 compatible?

### ISSUE THREAD

**Issue by mrjingles69** [google/google-api-php-client#900]
Hi, 

Is the latest version (at the time of writing this) of the Google API PHP Client compatible with PHP 5.4?

I read that it is in the README but when I try to run it on my webserver I receive an error which states:

"Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset()"

Looking into this error called by Guzzle I can see that curl_reset() is only valid in PHP 5.5 and onwards.

Is there an alternative version I can easily download that is PHP 5.4 compatible?

Thanks in advance, Paddy

**Comment by bshaffer** [comment]
Hey Paddy! Yes, there is a 5.4-compatible version (see the travis builds passing [here](https://travis-ci.org/google/google-api-php-client/jobs/116201171)). However, you will need to install your dependencies manually with composer rather than downloading the release, because it requires the use of **Guzzle5** rather than **Guzzle6**, which is the default.

Try [installing composer] and running this in the root of your project:

```
composer require guzzlehttp/guzzle:~5.2
composer require google/apiclient:~2.0@RC
```
