### ISSUE TITLE
Cache problem when using api from web and from CRON (v1.1.7 and older)

### ISSUE THREAD

**Issue by xorexore** [google/google-api-php-client#921]
I was having this message:

> PHP Warning:  fopen(/tmp/Google_Client/ff/ffa24692fa418d0e8650699ce98d8cc9): failed to open stream: Permission denied in Google/Cache/File.php on line 127

The problem was that CRON was creating folders with root user and web with www-data user.

I sort of fixed this executing this line before the new Google_Client():
`$client->setClassConfig("Google_Cache_File", 'directory', sys_get_temp_dir() . '/Google_Client_'.posix_getuid());`

It can also be sort of (permanently) fixed by changing 'Google/Config.php' in line 143 with this:

`'directory' => sys_get_temp_dir() . '/Google_Client_' . posix_getuid()`

This will create separate caches for each user that runs it, avoiding permission problems, but it may be a problem for some systems to have a lot of new temp folders.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.
