### ISSUE TITLE
Composer repo missing Sheets class

### ISSUE THREAD

**Issue by notredamstra** [google/google-api-php-client#962]
The composer repository is missing the Sheets.php file with the Sheets class, so the tutorial on https://developers.google.com/api-client-library/php/start/installation#requirements is not working properly when following the Composer installation instructions.

**Comment by bshaffer** [comment]
@notredamstra the sheets class (if you follow the tutorial) is available [here](https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Service/Sheets.php). Make sure you include the `-b v1-master` in your `git clone` command, so that you pull down the right branch. Also be sure you're including `vendor/autoload.php` at the top of your php file.

**Comment by nickrussell** [comment]
@bshaffer, it'd be great to provide clarity on including the Sheets.php services, as the documentation outlined in https://developers.google.com/sheets/quickstart/php explains that everything is provided as part of the composer install:

php composer.phar require google/apiclient:1.*

This does not include Sheets.php as part of the Google api package. Is there potentially a more curent google/apiclient:version that should be specified to include this?

**Comment by dadrados** [comment]
I'm with @nickrussell.

**Comment by bshaffer** [comment]
Thanks for reporting this! You're right, the command was not pulling in the `Sheets.php` file because it had not been tagged with a stable release.

I've tagged version `1.1.8` so this is now good to go. Try running the composer command again:

```sh
composer clear-cache
composer require google/apiclient:1.*
```
