### ISSUE TITLE
Write selectively to a range in spreadsheet not working with null values

### ISSUE THREAD

**Issue by madebyrogal** [google/google-api-php-client#979]
When I try write selectively value like in this example
https://developers.google.com/sheets/samples/writing#write_selectively_to_a_range

I get Google_Service_Exception code 400 message Invalid JSON payload received
But when I use not_null type instead null, everything is ok :)

```
$this->serviceSheet = new Google_Service_Sheets($this->googleClient); 
$this->valueRange = new Google_Service_Sheets_ValueRange(); 
$this->valueRange->setValues($data['columns']);
$this->valueRange->setMajorDimension('ROWS'); 
$response = $this->serviceSheet->spreadsheets_values->update($this->fileID, $data['range'], $this->valueRange, array("valueInputOption" => $this->valueInputOption));
```

where $data['columns'] is like in example:

`[[null,"$1","$2", ""], [], [null,"4/1/2016", "4/15/2016", ""]]`

**Comment by madebyrogal** [comment]
$this->serviceSheet = new Google_Service_Sheets($this->googleClient);

$this->valueRange   = new Google_Service_Sheets_ValueRange();

$this->valueRange->setValues($data['columns']);

$this->valueRange->setMajorDimension('ROWS');

$response = $this->serviceSheet->spreadsheets_values->update($this->fileID, $data['range'], $this->valueRange, array("valueInputOption" => $this->valueInputOption));

**Comment by madebyrogal** [comment]
where $data['columns'] is like in example:

'
[
    [null,"$1","$2", ""],
    [],
    [null,"4/1/2016", "4/15/2016", ""]
]
'

**Comment by bshaffer** [comment]
Have you tried using an empty string instead of null values?

**Comment by madebyrogal** [comment]
Yes, I tried, and it worked, but empty string like this '' delete value, but I wanted to skip value.

**Comment by bshaffer** [comment]
@madebyrogal can you inspect what your JSON payload looks like and add it here?

**Comment by bshaffer** [comment]
@madebyrogal have you tried using `Google_Model::NULL_VALUE`?

**Comment by biakaveron** [comment]
> @madebyrogal have you tried using Google_Model::NULL_VALUE?

works, thank you!

**Comment by rigalpatel001** [comment]
Not working 
```

   $client = new Google_Client();
    $client->setApplicationName("Client_Library_Examples");
    $client->setClientId($client_id);
    $client->setClientSecret($client_secret);
    $client->setRedirectUri($redirect_uri);
    $client->setAccessType('offline');   // Gets us our refreshtoken
   $client->setScopes(Google_Service_Sheets::SPREADSHEETS);
   Google_Model::NULL_VALUE;
   $service = new Google_Service_Sheets($client);
      
         $spreadsheetId = 'spredsheetid';
         //$sheetInfo = $service->spreadsheets->get($spreadsheetId)->getProperties();
         $options = array('valueInputOption' => 'RAW');
        $values = [["1",null,null,null,null,null,null,null,null,null,null,null,null,null]];
       $body   = new Google_Service_Sheets_ValueRange(['values' => $values]);    
      $result = $service->spreadsheets_values->update($spreadsheetId, "test- update todo!durationupdate", $body, $options);
```

**Comment by BARNZ** [comment]
Was just about to open an issue but luckily found this answer. Maybe it should be made more obvious that `Google_Model::NULL_VALUE` should be supplied in the dataset instead of actual php `null` values?

I traced the underlying issue down to the `getSimpleValue` function when processing an array and it encounters a php `null` value it skips adding it to the output array. This can lead to the output array becoming sparse / associative which when json encoded becomes a json object instead of an array. The resulting json is then rejected by the api:

`{"valueInputOption":"RAW","data":[{"majorDimension":"ROWS","range":"Sheet1!Y13:AJ13","values":[{"0":"","1":"","2":"","4":"","5":"","6":"","8":"14\/05\/2019","9":"07:00:00"}]}]}`

expected output:

`{"valueInputOption":"RAW","data":[{"majorDimension":"ROWS","range":"Sheet1!Y13:AJ13","values":[["","","",null,"","","",null,"14\/05\/2019","07:00:00"]]}]}`

**Comment by jzinkovich** [comment]
I'm have this same issue on the java-client, is there any resolution for java to this issue?

**Comment by pestka** [comment]
> @madebyrogal have you tried using `Google_Model::NULL_VALUE`?

This is unbelievable that it is nowhere to be found in google documentation. So much wasted time.
It is clear that google does not care about API documentation.
Thank you, sir.
