### ISSUE TITLE
v2.x version of this client not working with php 5.4

### ISSUE THREAD

**Issue by vishnupratap82** [google/google-api-php-client#985]
Hi Team,

I have my project on php 5.4 and was using v1 version of this php client so far. As i came to know about DFA upgrade to 2.5, i found out that v1 version of this php client supports only till DFA version 2.4, therefore i decided to use v2.x version of this php client to support DFA 2.5. When i download v2.0.1 php client from here https://github.com/google/google-api-php-client/releases and run it in my project, it gives following error 

Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /home/httpd/git-co/genesis_web/bin/lib/vendor/google-api-php-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

On googling this error i found out that "curl_reset()" doesn't work with php 5.4 but documentation of this php client says we can use v2.x version with php >= 5.4. Why is it so ? Can you suggest any workaround for this problem ?

**Comment by bshaffer** [comment]
@vishnupratap82 This is because the package available for downloads contains the installed dependencies for the platform it was installed on. To update the dependencies for your own platform, run the composer command locally:

```sh
cd /path/to/google-api-php-client-v2.0.1
composer install
```

Since this may be a common problem, I've made a [PHP 5.4 specific release](https://github.com/google/google-api-php-client/releases/tag/v2.0.1) available for download.
